In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [17]:

from pathlib import Path

TRANSCRIPT_PATH = "data/Transcripts/MSFT/2017-Jan-26-MSFT.txt"
PROCESSED_JSON_PATH = Path("data/processed/2017-Jan-26-MSFT.json")

from hedging_dataset_creator.sentence_tokenizer import sentence_tokenizer
from speech_parser.transcript_parser import parse_transcript_to_json
parse_transcript_to_json(TRANSCRIPT_PATH)
sentences = sentence_tokenizer(PROCESSED_JSON_PATH).iloc[:20, :]
sentences

                                             sentence
0                                Thank you, operator.
1   Good afternoon, and thank you for joining us t...
2   On the call with me today are Satya Nadella, C...
3   On our website, Microsoft.com/Investor, you ca...
4   Microsoft completed the acquisition of LinkedI...
5   Accordingly, our key investor metrics do not i...
6   Additionally, for Q2 only we're providing non-...
7   Our press release and slide deck contain suppl...
8   Unless otherwise specified, we will refer to n...
9   The non-GAAP financial measures provided shoul...
10  They are included as additional clarifying ite...
11  Additionally, any mention of operating expense...
12  All growth comparisons we make on the call tod...
13  We also provide growth rates in constant curre...
14  We will post our prepared remarks to our websi...
15   Today's call is being webcast live and recorded.
16  If you ask a question, it will be included in ...
17  You can replay the call and view the transcrip...
18  During this call, we will be making forward-lo...
19  These statements are based on current expectat...

In [18]:
from hedging_dataset_creator.hedging_labeller import hedging_labeller
data = hedging_labeller(sentences)
data

Labelling hedging sentences: 100%|██████████| 20/20 [00:23<00:00,  1.19s/sentence]

                                             sentence isHedge
0                                Thank you, operator.       0
1   Good afternoon, and thank you for joining us t...       0
2   On the call with me today are Satya Nadella, C...       0
3   On our website, Microsoft.com/Investor, you ca...       0
4   Microsoft completed the acquisition of LinkedI...       0
5   Accordingly, our key investor metrics do not i...       0
6   Additionally, for Q2 only we're providing non-...       0
7   Our press release and slide deck contain suppl...       0
8   Unless otherwise specified, we will refer to n...       0
9   The non-GAAP financial measures provided shoul...       1
10  They are included as additional clarifying ite...       0
11  Additionally, any mention of operating expense...       0
12  All growth comparisons we make on the call tod...       0
13  We also provide growth rates in constant curre...       0
14  We will post our prepared remarks to our websi...       0
15   Today's call is being webcast live and recorded.       0
16  If you ask a question, it will be included in ...       0
17  You can replay the call and view the transcrip...       0
18  During this call, we will be making forward-lo...       1
19  These statements are based on current expectat...       1

In [19]:
from dotenv import load_dotenv
load_dotenv()
print("success")

success